# Generated by Django 5.0.3 on 2024-03-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenormand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
